export const data = [
  {
    id: '1',
    brand: 'Adidas',
    name: 'Trefoil Ankle Socks 3 Pack',
    color: 'white',
    price: 11.99,
    pairs: 'three',
    favourite: false,
    amount: 123,
    onlyNew: 'onlyNew',
  },
  {
    id: '2',
    brand: 'Adidas',
    name: 'Solid Crew Sock 3 Pack',
    color: 'blue',
    price: 14.99,
    pairs: 'three',
    favourite: false,
    amount: 193,
    onlyNew: 'onlyNew',
  },
  {
    id: '3',
    brand: 'Adidas',
    name: 'Low Cut Socks 3 Pack',
    color: 'white',
    price: 14.99,
    pairs: 'three',
    favourite: false,
    amount: 223,
    onlyNew: '',
  },
  {
    id: '4',
    brand: 'Adidas',
    name: 'Low Cut Socks 3 Pack',
    color: 'black',
    price: 14.99,
    pairs: 'three',
    favourite: false,
    amount: 123,
    onlyNew: '',
  },
  {
    id: '5',
    brand: 'Adidas',
    name: 'Solid Crew Sock 3 Pack',
    color: 'orange',
    price: 14.99,
    pairs: 'three',
    favourite: false,
    amount: 93,
    onlyNew: '',
  },
  {
    id: '6',
    brand: 'Adidas',
    name: 'Mid Cut Crew Socks 3pack',
    color: 'white',
    price: 12.99,
    pairs: 'three',
    favourite: false,
    amount: 493,
    onlyNew: '',
  },
  {
    id: '7',
    brand: 'Dr. Martens',
    name: 'Pride Vertical Logo Socks',
    color: 'black',
    price: 8.99,
    pairs: 'one',
    favourite: false,
    amount: 33,
    onlyNew: '',
  },
  {
    id: '8',
    brand: 'Dr. Martens',
    name: 'Athletic Logo Socks',
    color: 'white',
    price: 9.99,
    pairs: 'one',
    favourite: false,
    amount: 433,
    onlyNew: 'onlyNew',
  },
  {
    id: '9',
    brand: 'Dr. Martens',
    name: 'Double Doc Socks',
    color: 'white',
    price: 9.99,
    pairs: 'one',
    favourite: false,
    amount: 193,
    onlyNew: '',
  },
  {
    id: '10',
    brand: 'Dr. Martens',
    name: 'Athletic Logo Socks',
    color: 'black',
    price: 8.99,
    pairs: 'one',
    favourite: false,
    amount: 233,
    onlyNew: '',
  },
  {
    id: '11',
    brand: 'Dr. Martens',
    name: 'Vertical Logo Socks',
    color: 'white',
    price: 8.99,
    pairs: 'one',
    favourite: false,
    amount: 144,
    onlyNew: 'onlyNew',
  },
  {
    id: '12',
    brand: 'New Balance',
    name: 'Nb Cotton Flat Knit Tie Dye 3 Pair Socks',
    color: 'red',
    price: 12.99,
    pairs: 'three',
    favourite: false,
    amount: 493,
    onlyNew: '',
  },
  {
    id: '13',
    brand: 'New Balance',
    name: 'Nb Cotton Flat Knit Tie Dye 3 Pair Socks',
    color: 'blue',
    price: 9.99,
    pairs: 'three',
    favourite: false,
    amount: 223,
    onlyNew: '',
  },
  {
    id: '14',
    brand: 'New Balance',
    name: 'Nb Cotton Flat Knit Tie Dye 3 Pair Socks',
    color: 'black',
    price: 5.99,
    pairs: 'three',
    favourite: false,
    amount: 431,
    onlyNew: 'onlyNew',
  },
  {
    id: '15',
    brand: 'Nike',
    name: 'Everyday Plus Socks 1 Pair',
    color: 'green',
    price: 9.99,
    pairs: 'one',
    favourite: false,
    amount: 93,
    onlyNew: '',
  },
  {
    id: '16',
    brand: 'Nike',
    name: 'Everyday Plus Socks 1 Pair',
    color: 'white',
    price: 9.99,
    pairs: 'one',
    favourite: false,
    amount: 341,
    onlyNew: '',
  },
  {
    id: '17',
    brand: 'Nike',
    name: 'Cushioned Tie Dye Crew Socks 2 Pairs',
    color: 'green',
    price: 12.99,
    pairs: 'two',
    favourite: false,
    amount: 432,
    onlyNew: '',
  },
  {
    id: '18',
    brand: 'Nike',
    name: 'Crew Socks 2 Pairs',
    color: 'orange',
    price: 12.99,
    pairs: 'two',
    favourite: false,
    amount: 123,
    onlyNew: 'onlyNew',
  },
  {
    id: '19',
    brand: 'Nike',
    name: 'Nike Sportswear Everyday Essential Ankle Socks 3 Pack',
    color: 'black',
    price: 12.99,
    pairs: 'three',
    favourite: false,
    amount: 231,
    onlyNew: '',
  },
  {
    id: '20',
    brand: 'Nike',
    name: 'Nike Sports Everyday Essential High 3 Pairs',
    color: 'white',
    price: 12.99,
    pairs: 'three',
    favourite: false,
    amount: 334,
    onlyNew: 'onlyNew',
  },
];

export default data;
